config/routes.rb
Quizery::Application.routes.draw do
  root "quizzes#index"

  resources :users

  resources :quizzes

  resources :scores

  get "/login", to: "session#new"
  post "/login", to: "session#create"
  delete "/logout", to: "session#destroy"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :quiz
  has_many :answers, :dependent => :destroy
  accepts_nested_attributes_for :answers, :allow_destroy => true
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  has_many :questions, :dependent => :destroy
  has_many :scores
  accepts_nested_attributes_for :questions, :allow_destroy => true


  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end

end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :quiz
  belongs_to :user
end

app/models/student.rb
class Student < User
end

app/models/teacher.rb
class Teacher < User
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :scores
  has_many :answers
  has_many :quizzes, through: :scores
  validates :email, presence: :true, uniqueness: :true 
  has_secure_password
  validates :password_digest, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  helper_method :current_user, :logged_in?


end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action(:load_quiz, { only: [:show, :destroy] })

  def index
    @quizzes = Quiz.search(params[:search])
    @all_quizzes = Quiz.all
    @all_quizzes.group_by(&:category)
    if current_user
      @user = User.find(current_user.id)
    end
  end

  def new
    @quiz = Quiz.new
    @quiz.questions.build
    @quiz.questions.each do |question|
      question.answers.build
    end
  end

  def show
    @questions = @quiz.questions
  end

  def create
    @quiz = Quiz.new(quiz_params)
    @quiz.category = params["category"]
    if @quiz.save
     redirect_to @quiz, notice: "Successfully created survey."
    else
      render :new
    end
  end

  def destroy
    @quiz.destroy
    redirect_to ('/')
  end

  private

  def load_quiz
    return @quiz = Quiz.find(params[:id])
  end

  def quiz_params
    params.require(:quiz).permit(:category, :name, :time_limit, :start_date, questions_attributes: [:query, :number, :time_limit, answers_attributes: [:name, :number, :correct]])
  end

end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController

  def index
  end

  def create
    find_quiz_name
    user_score = check_score
    if current_user
      @user = User.find(current_user.id)
      @score = @user.scores.create(quiz_id: params["quiz_id"].to_i, value: user_score.to_i, quiz_name: @quizname )
      render json: @score
    else
      @score = Score.create(quiz_id: params["quiz_id"].to_i, value: user_score.to_i, quiz_name: @quizname )
      render json: @score
    end
  end

  def check_score
    score = 0
    @answers = []
    params["answer"].each do |answer|
      @answers << Answer.find((answer.to_i))
    end
    @answers.each do |answer|
      if answer.correct == true
        score = score + 1
      end
    end
    score = (score.to_f / (params["answer"].length)) * 100
    return score
  end

  def find_quiz_name
    @quiz = Quiz.find(params["quiz_id"].to_i)
    @quizname = @quiz.name
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new 
  end

  def create
    user = User.find_by(email: params[:email])

    if user && ( user.authenticate(params[:password]) ) && user.type == "Student"
      session[:user_id] = user.id
      redirect_to ( '/' )

    elsif user && ( user.authenticate(params[:password]) ) && user.type == "Teacher" 
      session[:user_id] = user.id
      redirect_to ( '/' )

    elsif user && ( user.authenticate(params[:password]) ) 
      session[:user_id] = user.id
      redirect_to ( '/' )

    else
      redirect_to ('/')
      flash[:message] = 'Invalid email/password combination'
    end    
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, :authorize, only: [:edit, :update, :show]
  
  def index
  end

  def new
  end

  def show
    @dataset = []
    @quiznames = []
  end

  def create
    @user = User.new
    @user.email = params["email"]
    @user.first_name = params["first_name"]
    @user.last_name = params["last_name"]
    @user.password = params["password"]
    @user.password_confirmation = params["password_confirmation"]
    @user.type = params["type"]

    if @user.save
      session[:user_id] = @user.id
      redirect_to :back
    else
      render status: 400, nothing:true
    end

  end


  def student
    @student = User.find(session[:user_id])
  end

  def load_user
    return @user = User.find(params[:id])
  end 

  def authenticate
    unless logged_in?
      redirect_to root_path
    end
  end

  def authorize
    unless current_user == @user
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end
  
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quizery</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <ul class="nav">
    <li><%= link_to("Home", quizzes_path) %></li>
    <li class="logout"><%= link_to("Log Out", "/logout", method: "delete") unless session[:user_id].nil? %></li>
    <% if current_user && current_user.type == 'Student' %>
      <li><%= link_to("My Dashboard", user_path(current_user.id)) %></li>
    <% end %>
  </ul>

  <% unless @user.nil? %>
    <script>
      localStorage["user_id"] = <%= @user.id %>
    </script>
  <% end %>

<%= yield %>

</body>
</html>

app/views/quizzes/_answer_fields.html.erb
<p class = "fields">  
  <%= f.label :name, "Answer" %>
  <%= f.text_field :name %>
  <%= f.label "Correct Answer?" %>
  <%= f.check_box :correct %>
  <%= link_to_remove_fields "remove", f %>
</p>

app/views/quizzes/_form.html.erb
<div class="newQuiz">
  <%= form_for @quiz, :html => {:id => 'newQuizForm' } do |f| %>
    <p>
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </p>
    <p><%= select_tag(:category, options_for_select([['Math', 'Math'], ['Social Studies', 'Social Studies'], ['English', 'English'], ['Science', 'Science']])) %>
    </p>
    <p>
      <%= f.label :time_limit %><br />
      <%= f.text_field :time_limit %> Minutes
    </p>

    <p>
      <%= f.label :start_date %><br />
      <%= f.text_field :start_date %>
    </p>

    <%= f.fields_for :questions do |builder| %>
      <%= render 'question_fields', :f => builder %>
    <% end %>
    <p><%= link_to_add_fields "Add Question", f, :questions %></p>
    <p><%= f.submit "Save" %></p>
  <% end %>
</div>

<script>
  $("#quiz_start_date").datepicker({
    minDate: 0,
    dateFormat: "yy-mm-dd"
  });

  function remove_fields(link) {
    $(link).prev("input[type=hidden]").val("1");
    $(link).closest(".fields").hide();
  }

  function add_fields(link, association, content) {
    var new_id = new Date().getTime();
    var regexp = new RegExp("new_" + association, "g")
    $(link).parent().before(content.replace(regexp, new_id));
  }
</script>

app/views/quizzes/_question_fields.html.erb
<div class="fields"><p>
  <%= f.label :query, "Question" %>
  <%= link_to_remove_fields "remove", f %><br />
  <%= f.text_area :query, :rows => 3 %>
</p>
  <% f.fields_for :answers do |builder| %>
    <%= render 'answer_fields', :f => builder %>
  <% end %>
  <p><%= link_to_add_fields "Add Answer", f, :answers %></p>
</div>

app/views/quizzes/index.html.erb
<body class="quizindex">

  <% unless current_user %>
    <container class="indexNav">
      <div class="loginDiv">
        <button class="login">LOG IN <%= image_tag('arrowdown.png')%>
        </button>
        <div class="loginForm">
          <%= form_tag "/login" do %>
            <%= label_tag :email %>:
            <%= email_field_tag :email %></br>
            <%= label_tag :password %>:
            <%= password_field_tag :password %></br>
            <%= submit_tag "Log in!" %>
          <% end %>
        </div>
      </div>
      <div class="joinDiv">
        <button class="joinbutton">JOIN <%= image_tag('arrowdown.png')%>
        </button>
        <form class="joinForm" name='user' method="POST" action="/users">
          <select name='type'><option value='Student'>Student</option><option value='Teacher'>Teacher</option></select><br>
          Email:                 <input type='email', name='email'></input><br>
          Password:              <input type='password', name='password'></input><br>
          Password Confirmation: <input type='password', name='password_confirmation'></input><br>
          First Name:            <input type='text', name='first_name'></input><br>
          Last Name:             <input type='text', name='last_name'></input><br>
                                 <input type='submit', value='Save'></input> 

        </form>
      </div>
    </container>
  <% end %>

  <%= image_tag('quizerylogo.png') %>

  <div class="categories">
      <%= image_tag('english.png') %>
      <%= image_tag('science.png') %>
      <%= image_tag('globe.png') %>
      <%= image_tag('math.png') %>
  </div>

  <div class = "userNav">
    <% if current_user && @user.type == "Teacher" %>
      <%= link_to("Create A New Quiz", new_quiz_path) %>
    <% elsif current_user && current_user.type == "Student" %>
      <%= link_to("My Dashboard", user_path(@user)) %> 
    <% end %>
  </div>

  <%= form_tag quizzes_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>

    <h2> All Quizzes </h2>
    <div class="allQuizzesList">
      <% @quizzes.each do |quiz| %>
        <li><a href='/quizzes/<%= quiz.id %>'><button><%= quiz.name %></button></a></li>
      <% end %>
    </div>

    <div class="clearSpace">
    </div>

  <div class = "description">
    <div class="how">
      <h2> HOW DOES IT WORK? </h2>
    </div>

    <ul class="list">
      <li class="step">
        <%= image_tag("quizcreation.png") %>
        <span>Teachers can create custom, timed quizzes.</span>
      </li>
      <li class="step">
        <%= image_tag("score.png") %>
        <span>Students can complete quizzes and receive their scores.</span>
      </li>
      <li class="step">
        <%= image_tag("results.png") %>
        <span>Teachers and Students can view thier results!</span>
      </li>
    </ul>
  </div>



</body>


<script>
  $('.login').click(function(){
    $('.loginForm').toggle()
  })

  $(".joinbutton").on("click", function(){
    $(".joinForm").toggle();
  });
</script>


  

app/views/quizzes/new.html.erb
<h1>QUIZERY CREATION ZONE</h1> 
<hr>
<div class="createQuiz">
  <button class="instructionsButton">INSTRUCTIONS
  </button>
  <ol class="instructions">
    <li>Input a unique quiz name</li>
    <li>Select a category</li>
    <li>Input the time limit for the quiz in minutes</li>
    <li>Select the quiz start date</li>
    <li>Add multiple questions & answers</li>
    <li>Check the box of the correct answer</li>
    <li>SAVE QUIZ!</li>
  </ol>
</div>

<h2 class ="createNewQuiz">NEW QUIZ</h2>

<%= render 'form' %>

<script>
  $(".instructionsButton").on("click", function(){
    $(".instructions").toggle();
  })
</script>

app/views/quizzes/show.html.erb
<body class="startquiz">
  <% if @quiz.start_date <= DateTime.now.to_date %>
    <h1><%= @quiz.name %></h1>

  <% if current_user && current_user.type == "Teacher" %>
    <%= form_tag quiz_path(@quiz), method: "delete" do %>
      <%= submit_tag("Delete Quiz") %>
    <% end %>
    <%= link_to("Create New Quiz", new_quiz_path) %>
  <% end %>

  <button class="start_quiz">Start Quiz</button>

  <div id="timerClock">
    <div id="DateCountdown" data-timer="<%= @quiz.time_limit * 60 %>" class="ui-widget-content" style="width: 100%;">
    </div>
  </div>

  <div class ="quiz">
    <ol class="questions">
        <% @quiz.questions.each do |question| %>
        <li>
          <%= question.query %>
          <ol class="answers">
            <% question.answers.each do |answer| %>
            <li>
              <%= radio_button_tag("answer[#{question.id}]", answer.id) %>
              <%= label("answer_".concat(answer.id.to_s).to_sym, answer.name) %>
            </li>
            <% end %>
          </ol>
        </li>
        <% end %>
    </ol>

  <div><%= submit_tag("Submit", :class => "submit") %></div>

  </div>

  <% else %>
    <h4>Sorry this quiz is not available yet. It will be available on <%= @quiz.start_date %></h4>
  <% end %>

</body>


<script>

  $("#DateCountdown").draggable()

  $(".submit").on("click", function(){
     $.ajax({
        url: "/scores",
        type: "POST",
        data: {quiz_id: <%= @quiz.id %>, answer: _.map($("input:checked"), function(choice){return choice.getAttribute("value")}) },
        
        success: function(response) {
            $("body").append($("<div class ='quiz_score'>QUIZ SCORE:" + response.value + "% </div>"))
            $(".quiz").remove(); 
            $(".submit").remove();
            $(".start_quiz").remove();
        }
      });
  })

  $(".start_quiz").on("click", function(){
    $(".quiz").slideDown("300") 
    $("#DateCountdown").TimeCircles({
      "animation": "smooth",
      "bg_width": 1.2,
      "fg_width": 0.13333333333333333,
      "circle_bg_color": "#212121",
      "time": {
        "Days": {
          "text": "Days",
          "color": "#FFCC66",
          "show": false
        },
        "Hours": {
          "text": "Hours",
          "color": "#99CCFF",
          "show": false
        },
        "Minutes": {
          "text": "Minutes",
          "color": "#8DC549",
          "show": true
          },
        "Seconds": {
          "text": "Seconds",
          "color": "#FF9999",
          "show": false
        }
      }
    });
  $("#DateCountdown").TimeCircles({count_past_zero: false}); 
});

</script>

app/views/users/show.html.erb
<h1>MY RESULTS</h1>
<hr>

  <% @user.scores.each do |score| %>
    <% @dataset << score.value %>
    <div class = "quiznames">
      <li><strong>Quiz Name:</strong> <%= score.quiz_name %>
        <li><strong>Score:</strong> <%= score.value %>%
        </li>
      </li>
    </div>
  <% end %> 
 
<h2>Quiz Progress</h2>

<div class="graph">
</div>

<script>
  var dataset = <%= @dataset %>

  for(var i = 0; i < dataset.length; i++){
    $(".graph").append($("<div style= 'height:"+ dataset[i] * 2 + "px;' class='bar'>" + dataset[i] + "%</div>"))
  }
</script>